name: amd64_windows_clang

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:

  amd64_windows_clang:
    runs-on: windows-2019
    env:
      CC: clang
      CXX: clang++
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - uses: actions/checkout@v2
    - run: echo "::add-path::C:\\msys64\\usr\\bin"
    - run: pacman --version
    - run: pacman -Sy
    - run: pacman --noconfirm -S pacman-mirrors
    - name: 'Install requirements'
      run: pacman --noconfirm -S mingw64/mingw-w64-x86_64-clang mingw64/mingw-w64-x86_64-cmake mingw64/mingw-w64-x86_64-qtwebkit mingw64/mingw-w64-x86_64-python2
    - run: echo "::add-path::C:\\msys64\\mingw64\\bin"
    - run: clang++ --version && cmake --version && qmake --version
      name: 'Display tools version'
    - run: bash ./configure
      name: './configure'
      env:
        CMAKE_CMD: 'cmake -G "MinGW Makefiles"'
    - run: mingw32-make
      name: 'make'
    - run: file ./bin/phantomjs
    - run: ldd ./bin/phantomjs
    - run: ./bin/phantomjs --version

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: amd64_windows_clan_phantomjs_bin
        path: ./
