name: amd64_linux_gcc

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:

  amd64_linux_gcc:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt -y -qq update
    - run: sudo apt install -y g++ cmake qt5-default libqt5webkit5-dev python
      name: Install requirements
    - run: g++ --version && cmake --version && qmake --version && python --version
      name: Display tools version
    - run: ./configure
    - run: make
    - run: file ./bin/phantomjs
    - run: ./bin/phantomjs --version
    - run: make check

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: amd64_linux_gcc_phantomjs_bin
        path: ./bin
